# Generated by Django 4.0.4 on 2022-09-21 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(choices=[('Flats', 'Flats'), ('Apartments', 'Apartments'), ('Bungalow', 'Bungalow'), ('Offices', 'Offices'), ('Studentresidence', 'Studentresidence'), ('Bedsitters', 'Bedsitters'), ('Singleroom', 'Singleroom')], max_length=20, null=True)),
                ('bathroom', models.CharField(max_length=50, null=True)),
                ('kitchen', models.CharField(max_length=50, null=True)),
                ('bedroom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default='blank.jpeg', upload_to='profile_images')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Houselocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('maxprice', models.IntegerField()),
                ('minprice', models.IntegerField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Houselocation_category', to='Keja.category')),
            ],
        ),
    ]
