# Generated by Django 3.2.15 on 2022-09-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
    ]
