# Generated by Django 3.2.15 on 2022-10-31 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keja', '0002_remove_category_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
